### ISSUE TITLE
Linker error leads to missing symbols on builds with lots of object files

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#13193]
We stumbled upon a strange behavior in our project.
It seems that when using a non `--release` version of the binary and trying to run it we get the error: 

```crystal
/bin/whatever: symbol lookup error: ./bin/whatever: undefined symbol: environ, version Hash(K, V)#update_linear_scan<String, Devtools::Protocol::Media::PlayersCreated.class, UInt32>:(Hash::Entry(String, Devtools::Protocol::ProtocolEvent+.class) | Nil)
```

It gets even stranger when looking at it with `ldd -d` 

`shards build whatever -p --release --debug --error-trace`:

```
ldd -d bin/whatever
	linux-vdso.so.1 (0x00007ffc22d45000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007fa31cc98000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fa31fae5000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fa31facb000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007fa31cbf8000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007fa31c600000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fa31cb7e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fa31ca96000)
	libgc.so.1 => /usr/lib/libgc.so.1 (0x00007fa31c594000)
	libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x00007fa31c542000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa31ca76000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa31c35b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa31fbd8000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fa31c328000)
	libicuuc.so.72 => /usr/lib/libicuuc.so.72 (0x00007fa31c000000)
	libicudata.so.72 => /usr/lib/libicudata.so.72 (0x00007fa31a200000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fa319e00000)

```

`shards build whatever -p --debug --error-trace`:

```
ldd -d bin/whatever
	linux-vdso.so.1 (0x00007fff3ad53000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f9459698000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f94595f5000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f945dc58000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f9459555000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f9459000000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f94594db000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f9458f18000)
	libgc.so.1 => /usr/lib/libgc.so.1 (0x00007f945946f000)
	libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x00007f945dc04000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f945944f000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9458d31000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f945dcc2000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f9458cfe000)
	libicuuc.so.72 => /usr/lib/libicuuc.so.72 (0x00007f9458a00000)
	libicudata.so.72 => /usr/lib/libicudata.so.72 (0x00007f9456c00000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f9456800000)
undefined symbol: environ, version Channel::SelectContext(S)#try_trigger:Bool	(bin/whatever)
undefined symbol: __libc_start_main, version Slice(T)#swap<Int32, Int32>:Slice(Tuple(Awscr::Signer::Header, String))	(bin/whatever)

```

More strangely, this can be also avoided with adding `--single-module` to the build command `shards build whatever -p --debug --error-trace --single-module`:

```
 ldd -d bin/whatever
	linux-vdso.so.1 (0x00007ffee6bed000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f21aa498000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f21ade0a000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f21addf0000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f21aa3f8000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f21a9e00000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f21aa37e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f21aa294000)
	libgc.so.1 => /usr/lib/libgc.so.1 (0x00007f21a9d94000)
	libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x00007f21a9d42000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f21aa274000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f21a9b5b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f21adefd000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f21a9b28000)
	libicuuc.so.72 => /usr/lib/libicuuc.so.72 (0x00007f21a9800000)
	libicudata.so.72 => /usr/lib/libicudata.so.72 (0x00007f21a7a00000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f21a7600000)

```

I sadly do not have any minimal code example to provide that I can say caused this, it only happens in our full project.
Some things I can maybe add is that we have a BIG project, I think at this point this is the largest Crystal codebase out there, maybe second only to the compiler.
```
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Crystal                        1659          24326          18108         166374

```

When compiling we see 6102 objects in codegen stage (relevant? :shrug: )
 
If I can offer more information or data let me know :pray:

**Comment by HertzDevil** [comment]
What is the output of `crystal --version`?

**Comment by jwoertink** [comment]
I'm getting this too when running `crystal spec`. 

```
❯ crystal spec 
/home/jeremy/.cache/crystal/crystal-run-spec.tmp: symbol lookup error: /home/jeremy/.cache/crystal/crystal-run-spec.tmp: undefined symbol: environ, version Float::Printer::print<Float32, String::Builder>:Nil
```

The error changes depending on which files I run specs again, and which classes I have commented out, but it's always a similar undefined symbol. I've tried Crystal 1.7, 1.8, 1.9, and 1.10. With LLVM 13, 14, and 15. 

This seems to happen when I have too many classes required. If I comment out a chunk of my files, the specs pass. Also strange that I can actually boot my application just fine. I just can't run specs at all.

**Comment by jwoertink** [comment]
@bararchy It looks like adding then ENV `CC="cc -fuse-ld=lld"` might work around the issue. I tried using the `--single-module` flag, but it seems like that flag doesn't work on specs?

```
CC="cc -fuse-ld=lld" crystal spec
```

That allows us to run our specs now. @HertzDevil if there's any info I can provide, or anything you'd like me to try out, let me know. I haven't been able to reduce this to small code yet, but it's very reproducible for me.

**Comment by jwoertink** [comment]
Also wanted to link to a previous issue where this was happening https://github.com/crystal-lang/crystal/issues/7177#issuecomment-586710784 @bcardiff  had this solution.

**Comment by Blacksmoke16** [comment]
Not sure if it's the same issue, but was able to reproduce something very similar:

```cr
PII = 3.14

CONFIG = {float: 0.0}

{%
  CONFIG[:float] = PII
%}

CONFIG[:float] == PII
```

Results in:

```sh
$ crystal run test.cr
/usr/bin/ld: _main.o: in function `__crystal_main':
/home/george/test.cr:9:(.text+0x413): undefined reference to `PII'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with exit status 1: clang "${@}" -o /home/george/.cache/crystal/crystal-run-test.tmp  -rdynamic -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -levent -lrt -lpthread -ldl
```

**Comment by ysbaddaden** [comment]
I just reproduced the exact same linker error but with another symbol while trying to run the std spec. It always fails with:

```
std_spec: symbol lookup error: std_spec: undefined symbol: __libc_start_main, version Pointer(T)#+<Int32>:Pointer(Slice(Int32))
```

I can build execute any other crystal program successfully (including the compiler). I can also run the crystal std specs from a docker image (`crystallang/crystal:1.10-alpine`) so there is something wrong happening on my host.

My host: Ubuntu 20.04 / GCC 9.4 / LLVM 16. I also tried Clang 16 and of course clearing the crystal cache. I didn't try lld.

**Comment by straight-shoota** [comment]
I suspect this has something to do with the size of the binary, or the number of symbols. Something like that. `std_spec` is fairly huge because it contains the entirety of the standard library plus the tests. It has much more code than most other Crystal programs.

**Comment by straight-shoota** [comment]
I think this is exactly the same problem as #7177: The number of object files that we can pass as arguments to the linker on Linux is limited (apparently to 4096).

This only happens for *very* large code bases. Even the compiler is fine. But the stdlib specs seem to exceed it, as do other large programs.
For the Crystal repo we added a workaround in the Makefile to use `lld` (if available) instead of `ld` (#8641). Apparently `lld` doesn't have this restriction (or a higher limit that hasn't been exceeded yet).

Configuring to use `lld` prevents the problem for a specific build (or configuration). But we need a generic solution to make large code bases work with the standard linker on linux.

There is actually a quite similar problem on Windows, except that the limit is on the entire string length of the process arguments, not the number of individual arguments. And this limit is far easier to reach even with smaller code bases.

We've had a proper fix on Windows for a long time (#9062): If the arguments are too long, write them to a file and tell the linker to read from there. The syntax for this is `@file`. It is supported on Windows (`cl.exe`) as well as on Linux (`gnu-ld`, `lld` `gold`, ...). So I presume we should be able to use the same mechanism on Linux.

This issue hasn't been reported on BSD-based systems (including macOS) yet, so I don't think it's an issue there.

**Comment by straight-shoota** [comment]
Writing a patch for this is relatively straightforward. But validating if it fixes the issue is harder than I thought.
Does anyone have a simple reproduction with a (relatively) low number of object files?

I've managed to link up to about 31k object files using the code from https://github.com/crystal-lang/crystal/issues/7177#issuecomment-455719732. But I can reach the same number without the patch as well (tested in docker images `crystallang/crystal:1.7.3-build` and `crystallang/crystal:1.10.1-build`).
More than 31k object files fails regardless of whether the arguments are written to a file or not.

The failing threshold is significantly higher than some numbers reported in #7177. So we might be scratching a completely different limit and the original issue was resolved at some point or it doesn't reproduce in the cases that I tested.

Maybe someone can try the patched compiler on their code (assuming the failing condition still reproduces with a stock compiler).

This is my branch: https://github.com/straight-shoota/crystal/tree/feat/link-command-args-file

Note: Regardless of whether this fixes a linking problem, I already find it quite pleasant to reduce the noise whith `--verbose`. If you want to check which linker command is used, you don't need to see all the object file names. Putting them in a file makes a lot of sense (you can still go look there if you're curious).

**Comment by jwoertink** [comment]
I'm not sure how to reduce the code for easier testing, but I can say that the branch gives me different results...

```
❯ crystal spec 
/home/jeremy/.cache/crystal/crystal-run-spec.tmp: symbol lookup error: /home/jeremy/.cache/crystal/crystal-run-spec.tmp: undefined symbol: environ, version Avram::Validations#validate_required<Avram::Attribute(String)+>:Bool

❯ /home/jeremy/Development/crystal/shoota-crystal/bin/crystal spec 
Using compiled compiler at /home/jeremy/Development/crystal/shoota-crystal/.build/crystal
Showing last frame. Use --error-trace for full trace.

In spec/actions/api/oauth/token_spec.cr:16:32

 16 | action = Api::Oauth::Token.with(
                                 ^---
Error: missing arguments: client_id, refresh_token

❯ CC="cc -fuse-ld=lld" GC_DONT_GC=1 crystal spec
.........................................................................................
Finished in 17.68 seconds
547 examples, 0 failures, 0 errors, 1 pending
```

The 2 arguments it says I'm missing have a default value of `nil` if that makes any different.

**Comment by straight-shoota** [comment]
Thanks for testing!
My patch is just a single commit that only affects the linker command. 
Maybe some other change on `master` is interfering here. Or anything else? It's pretty much impossible that my change has any effect on the semantics of a program.

Could you cherry-pick the last commit from my branch on top of the commit of the working compiler version and try again?

**Comment by jwoertink** [comment]
Alright, I took the `1.12.1` branch, and applied that single commit and that gives me this

```
❯ /home/jeremy/Development/crystal/lang/bin/crystal spec 
Using compiled compiler at /home/jeremy/Development/crystal/lang/.build/crystal
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: cc @/home/jeremy/.cache/crystal/home-jeremy-Sites-joysticktv-spec/object_names.txt -o /home/jeremy/.cache/crystal/crystal-run-spec.tmp  -rdynamic -L/usr/bin/../lib/crystal -lxml2 -lgmp -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre2-8 -lm -lgc -lpthread -levent -lrt -lpthread -ldl
```

**Comment by straight-shoota** [comment]
Hm, that's not what I was expecting 🙈 It's quite interesting because it's now an error in the linker, not the loader (build error vs. run error).

And I can reproduce exactly the same behaviour with `make std_spec EXPORT_CC=`.

**Comment by straight-shoota** [comment]
Oh no. I think I messed up the generation of the arguments file. Was working on this quite late yesterday... 🤦
I don't know why I didn't notice that. My isolated test case certainly worked 😕

Anyway, I pushed a fixup commit. But now we're back to the loader error 😢
So it seems to not matter where `ld` reads the object files from, it just can't handle too many of them.

**Comment by ysbaddaden** [comment]
@straight-shoota I'm trying your patch. I can't compile/run the whole std specs on my Ubuntu 20.04, I must always go through an Alpine docker image.

**Comment by ysbaddaden** [comment]
Still no luck, even after fixing the `object_names.txt` file generation. I get:

```console
$ .build/std_spec 
.build/std_spec: symbol lookup error: .build/std_spec: undefined symbol: __libc_start_main, version Array(T)#dup:Array(SemanticVersion)
```

The symbol exists but it has a GLIBC version, and trying to run the executable is failing to find the symbol and reports an unrelated symbol as the version :raised_eyebrow:

```console
~/work/crystal-lang/crystal $ objdump -t .build/std_spec  | grep libc
0000000000000000       F *UND*  0000000000000000              gnu_get_libc_version@@GLIBC_2.2.5
0000000000000000       F *UND*  0000000000000000              __libc_start_main@@GLIBC_2.2.5
0000000000000000  w    O *UND*  0000000000000000              __libc_stack_end@@GLIBC_2.2.5
00000000022bd4b0 g     F .text  0000000000000065              __libc_csu_init
00000000022bd520 g     F .text  0000000000000005              __libc_csu_fini
```

More dabbling with objdump seems to confirm it:
```console
$ objdump -x .build/std_spec > /dev/null
objdump: .build/std_spec: .gnu.version_d invalid entry
objdump: warning: private headers incomplete: bad value
```

Fails on Ubuntu 20.04 / GCC 9.4.0 / LD (binutils) 2.34
Succeeds on Alpine Linux (edge) / GCC 13.2.1 / LD (binutils) 2.42

**Comment by ysbaddaden** [comment]
Maybe related: https://sourceware.org/bugzilla/show_bug.cgi?id=29566 (I'm not sure)

**Comment by straight-shoota** [comment]
I updated my branch to *always* write object file names to a file and pass that file to the linker (unless there's just a single object file, e.g. with `--single-module`).
This is probably what we want in the end anyways because it makes `--verbose` output readable instead of dumping pages of mangled object names which usually don't tell much. If you still want to read them, you can look in the file.

However, as mentioned previously in https://github.com/crystal-lang/crystal/issues/13193#issuecomment-2104559037, the error is still happening. Putting object names in a file doesn't seem to fix anything (it's probably still a good thing, though).

**Comment by straight-shoota** [comment]
I did a bit of comparison between different linkers. lld and mold work. ld (GNU linker) and gold experience the error we're discussing here.

**Comment by straight-shoota** [comment]
I think we should check for the existence of `lld` and implicitly configure using that as the linker when available. At least on Linux, maybe on other platforms as well.
It's always better than GNU ld.
Basically, this would incorporate our private configuration override from the Makefile into the compiler proper.

Of course this implicit configuration should only apply if the `CC` environment variable is unconfigured and no `-fuse-ld` link flag is set.

We could also look for `mold` and even prefer that over `lld`.

**Comment by ysbaddaden** [comment]
I get the same issue on NetBSD 10.1 with the std specs. I can't get `ld.lld` to be used, or something.

Workarounds are:

- `--single-module` to avoid the issue completely;
- `--static` to build a static executable.

**Comment by straight-shoota** [comment]
I get the `--single-module` workaround as that builds a single object file.
But `--static` seems odd...

**Comment by ysbaddaden** [comment]
Compiling statically means no more dynamic linker involved at runtime, which is what's actually failing — likely because of link-time bug.

On NetBSD it failed with symbols from external libraries (libxml, PCRE2), and a static executable just worked.

I haven't tested with glibc on Linux.
