### ISSUE TITLE
Regexp segfault

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2160]
(osx) it happens on special binary data, so i encode it with base64 to reproduce here:

``` crystal
require "base64"
f = Base64.decode_string("iVBORw0KGgoAAAANSUhEUgAAAtgAAABjCAY=")
f.scan(/[^=]*ABC/i) { |x| p x }
```

```
Using compiled compiler at .build/crystal
Invalid memory access (signal 10) at address 0x10f159fff
[4546807691] *CallStack::print_backtrace:Int32 +107
[4546790743] __crystal_sigfault_handler +55
[4546907779] sigfault_handler +35
[140735689663914] _sigtramp +26
[4547386049] pcre_exec +34569
[4547354498] pcre_exec +3018
[4546901377] *Regex#match_at_byte_index<Regex, String, Int32>:Regex::MatchData? +241
[4546788828] __crystal_main +3292
[4546796424] main +40
```

**Comment by asterite** [comment]
I reduced it to this:

```crystal
string = String.new(3) do |buffer|
  buffer[0] = 137_u8
  buffer[1] = 99_u8
  buffer[2] = 6_u8
  {3, 0}
end
string.scan(/.*ABC/i)
```

If I remove [NO_UTF8_CHECK](https://github.com/manastech/crystal/blob/master/src/regex/regex.cr#L227) it doesn't crash anymore.

Maybe this is another good reason to disallow Strings with invalid UTF-8 chars in them...

But I don't know why PCRE crashes, it shouldn't, my guess is that it's a PCRE bug.

**Comment by kostya** [comment]
how i can create regex with utf8 check? maybe by some option?

```crystal
r = Regex.new("[^=]*ABC", Regex::Options::IGNORE_CASE | Regex::Options::UTF_8)
f.scan(r) { |x| p x }
```

not working.

**Comment by asterite** [comment]
There's another thing: `Base64.decode` should probably return a slice.

There's no way to force the UTF-8 check. We removed it for performance reasons, but maybe we should always use it, or validate on our side.

We need to solve how to deal with String vs. Slice(UInt8) or what to do with invalid Strings... I'll soon open a new issue tracking this.

**Comment by ysbaddaden** [comment]
`Base64.decode` already returns a Slice(UInt8) thanks to @jhass. We have `Base64.decode_string` to return a String, and per the documentation it will raise if it's invalid UTF-8.

**Comment by asterite** [comment]
So fast! And without commits! :-)

(sorry, bad memory)

**Comment by straight-shoota** [comment]
Seems like this is fixed, all examples run fine in current compiler (0.24.1).

**Comment by kostya** [comment]
no still crashed on osx.

**Comment by vlazar** [comment]
@kostya Can you verify it's still an issue for you?

I've checked all examples from this issue and see no crashes on MacOS.

```
$ crystal --version
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

Example 1 (produces no output)
```crystal
require "base64"
f = Base64.decode_string("iVBORw0KGgoAAAANSUhEUgAAAtgAAABjCAY=")
f.scan(/[^=]*ABC/i) { |x| p x }
```

Example 2 (produces no output)
```crystal
string = String.new(3) do |buffer|
  buffer[0] = 137_u8
  buffer[1] = 99_u8
  buffer[2] = 6_u8
  {3, 0}
end
string.scan(/.*ABC/i)
```

Example 3 (produces no output)
```crystal
require "base64"
f = Base64.decode_string("iVBORw0KGgoAAAANSUhEUgAAAtgAAABjCAY=")
r = Regex.new("[^=]*ABC", Regex::Options::IGNORE_CASE | Regex::Options::UTF_8)
f.scan(r) { |x| p x }
```

**Comment by kostya** [comment]
fixed
