### ISSUE TITLE
Typo in Channel causes break

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#8704]
code to trigger is using select

```crystal
      select
      when data = chan.recieve
        data.to_http
      when timeout_chan.receive
        raise IO::Timeout.new
      end
```

```crystal
 334 | when data = chan.recieve
                        ^------
Error: undefined method 'recieve_select_action' for Channel(Nil)

Did you mean 'receive_select_action'?
```

**Comment by bcardiff** [comment]
Fixed by #8705

**Comment by Sija** [comment]
@bcardiff It's not really fixed, the issue here is cryptic error message related to the potential typo.

**Comment by bcardiff** [comment]
I agree that the errors introduced by syntax sugar transformation are more cryptic than they should be.

Another example of those are:

```cr
class Foo
end
 
Foo{1,2,3}
# error in line 4
# Error: undefined method '<<' for Foo
```

We can open another issue to frame the issue differently and cover other cases.
